### ISSUE TITLE
Split `popolo` method as `popolo_path` and `popolo_url`

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-ruby#1]
Rather than simply providing a somewhat ambiguous `popolo` method, we should provide separate `popolo_path` and `popolo_url` methods (or maybe even only the _url version — do people really need the `path` other than to construct a URL?)

That would then future-proof against `countries.json` switching from local paths to full URLs, and even free `.popolo` up to return the full JSON itself.

**Comment by chrismytton** [comment]
Now that [everypolitician-popolo](https://github.com/everypolitician/everypolitician-popolo) exists it would make sense for the `.popolo` method to return an instance of `Everypolitician::Popolo::JSON`.
