### ISSUE TITLE
Find a country based on an EP.org URL slug

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-ruby#17]
On EveryPolitician.org we have to go from a URL (e.g. http://everypolitician.org/congo-brazzaville/ or http://everypolitician.org/el-salvador/legislative-assembly) to the country and/or legislature given. 

As far as I can see, none of the constructors here allow for a search based on this form (i.e. against `slug.downcase`), but it would be nice if we had one. (If we do already have it, this becomes a request for documentation instead!)

**Comment by tmtmtmtm** [comment]
@octopusinvitro now that you've unlocked your Level 1 ★ with #16, want to take this one on next?

**Comment by octopusinvitro** [comment]
Sure :+1: !
