### ISSUE TITLE
Failing to `find` a Country shouldn't trigger an exception

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-ruby#38]
`Everypolitician::Country.find('Narnia')` should simply return nil, not throw an Exception.

**Comment by tmtmtmtm** [comment]
@chrismytton want to persuade us that this _should_ throw an Exception, or are we good to make this change?

**Comment by chrismytton** [comment]
No objections from me! It's probably worth making the same change for [legislatures](https://github.com/everypolitician/everypolitician-ruby/blob/1463ece0e717e9a35d39e0d8ebceafc33712d88b/lib/everypolitician.rb#L73) while doing this, as it's essentially the same.
