### ISSUE TITLE
Add method to Legislature that returns the path component of the names.csv URL

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-ruby#49]
The Legislature class should provide a method to return the path component of the URL of the names.csv file for the given legislature.
## Example:

The download.erb template in view-sinatra accesses the URL from the raw data:`house[:names]`.
(Example return value: `data/Bosnia_and_Herzegovina/House_of_Representatives/names.csv`)

It should be accessed like so: `house.names`

**Comment by tmtmtmtm** [comment]
I'm not so sure that `house.names` is the right name for this — I would expect that to return me a list of names, not a URL.

I'd probably make this `names_url` (cf: `csv_url` vs `csv`)
