### ISSUE TITLE
country.lower_house and country.upper_house

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-ruby#61]
Rather than needing to know the slug for a legislature, it should be possible to ask for things like `.country('UK').lower_house`

I'm not 100% sure what you should do in the case of a unicameral country — perhaps both should work?

**Comment by tmtmtmtm** [comment]
Most legislatures should now have a 'type' set to either 'upper house', 'lower house', or 'unicameral legislature', e.g.: https://github.com/everypolitician/everypolitician-data/blob/e6e7a1f5c33773c9bbbf2e3a787b0897bf48f57c/data/Pitcairn/Island_Council/ep-popolo-v1.0.json#L1013

(the others will appear next time that legislature is re-built)

We probably want to to expose this in `countries.json`, making it simple to provide access here.

**Comment by struan** [comment]
Yes, I would say we do want to expose this is `countries.json`
